
services:
  mtt:
    image: ghcr.io/buckaroobanzay/mtt:latest
    volumes:
     - "./:/github/workspace"
    environment:
     INPUT_MODNAME: "building_lib"
     INPUT_TEST_MODE: "mod"
     INPUT_MAPGEN: "singlenode"
     INPUT_GIT_GAME_REPO: "https://github.com/minetest/minetest_game"
     INPUT_GIT_DEPENDENCIES: |
      https://github.com/BuckarooBanzay/mtzip.git
      https://github.com/BuckarooBanzay/promise.git
      https://github.com/BuckarooBanzay/mapblock_lib.git
      https://github.com/mt-mods/wield_events.git
     INPUT_ADDITIONAL_CONFIG: |
      building_lib.enable_example_buildings = true