name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buckaroobanzay/mtt@main
      with:
        git_dependencies: |
          https://github.com/BuckarooBanzay/mtzip.git
          https://github.com/BuckarooBanzay/promise.git
          https://github.com/BuckarooBanzay/mapblock_lib.git
        additional_config: |
          building_lib.enable_example_buildings = true